<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "callBack".
 *
 * @property int $id
 * @property int $created_at
 * @property int $done_at
 * @property int $viewed
 * @property string $name
 * @property string $phone
 * @property string $lastName
 */
class CallBack extends \yii\db\ActiveRecord
{
    public $lastName;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'callBack';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone'], 'required'],
            [['created_at', 'done_at', 'viewed'], 'integer'],
            [['name', 'phone', 'lastName'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Дата заявки',
            'done_at' => 'Дата обработки',
            'viewed' => 'Состояние',
            'name' => 'Имя',
            'phone' => 'Телефон',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->created_at){

            $this->created_at =
                is_string($this->created_at)
                    ? strtotime($this->created_at)
                    : $this->created_at;
        }else{
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
