<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property int $id
 * @property int $created_at
 * @property int $done_at
 * @property int $viewed
 * @property string $user_name
 * @property string $text
 * @property string $email
 * @property int $publish
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'user_name'], 'required'],
            [['viewed', 'publish'], 'integer'],
            [['created_at', 'done_at'], 'safe'],
            [['text'], 'string'],
            [['user_name', 'email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Дата создания',
            'done_at' => 'Дата изменения',
            'viewed' => 'Просмотрен',
            'user_name' => 'Отзыв от',
            'text' => 'Текст отзыва',
            'email' => 'Email',
            'publish' => 'Состояние',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->created_at){

            $this->created_at =
                is_string($this->created_at)
                    ? strtotime($this->created_at)
                    : $this->created_at;
        }else{
            $this->date = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
